package com.policyinsight.service;

import com.policyinsight.ai.dto.CitedClaim;
import com.policyinsight.ai.dto.RiskReport;
import com.policyinsight.model.DocumentChunk;
import java.util.List;
import java.util.UUID;
import org.springframework.stereotype.Component;

@Component
public class FallbackReportBuilder {

    public static final String FALLBACK_LABEL = "Demo fallback. Not live AI analysis.";

    public RiskReport build(List<DocumentChunk> chunks) {
        List<UUID> primarySources = chunks.stream()
                .limit(3)
                .map(DocumentChunk::getId)
                .toList();
        UUID first = chunks.getFirst().getId();
        UUID second = chunks.size() > 1 ? chunks.get(1).getId() : first;
        UUID last = chunks.getLast().getId();

        return new RiskReport(
                FALLBACK_LABEL + " PolicyInsight extracted the document text and prepared a basic review checklist from the available source sections.",
                List.of(
                        claim("Review the extracted source text for payment, renewal, service, and acceptance terms.", primarySources),
                        claim("Confirm operational responsibilities and approval windows against the cited sources.", List.of(first, second)),
                        claim("Use this fallback report only as a demo-style starting point until live AI analysis succeeds.", List.of(first))
                ),
                List.of(
                        claim("Identify who must provide access, approvals, notices, data, or services.", List.of(first)),
                        claim("Confirm payment or performance obligations before relying on the agreement.", List.of(second)),
                        claim("Check whether any obligations depend on schedules, statements of work, or exhibits.", List.of(last))
                ),
                List.of(
                        claim("Look for limits on data use, assignment, scope changes, confidentiality, or service exclusions.", primarySources),
                        claim("Confirm whether out-of-scope work requires written approval or a change order.", List.of(last))
                ),
                List.of(
                        claim("Review breach, cure, nonpayment, renewal, and transition-assistance language.", primarySources),
                        claim("Confirm what fees, expenses, or duties survive termination.", List.of(last))
                ),
                List.of(
                        claim("Review closely: this fallback was not generated by live AI and may miss document-specific issues.", List.of(first)),
                        claim("Check deadlines that could trigger deemed acceptance, late fees, termination rights, or waiver.", primarySources),
                        claim("Validate liability limits, remedies, governing law, venue, and excluded services directly against the source text.", List.of(last))
                )
        );
    }

    private CitedClaim claim(String text, List<UUID> sourceIds) {
        return new CitedClaim(text, sourceIds, false);
    }
}
